export const SUBREDDITS = [
  // Freelance & hiring focused
  "forhire",
  "hiring",
  "freelance",
  "freelance_forhire",
  "FreelanceIndia",
  "hiringcafe",
  "jobs",
  "webdev",
  "reactjs",
  "INFreelancers",
  // Startup opportunities
  "cofounder",
  "Startup_Ideas",
  "StartupAccelerators",
  "StartUpIndia",
  "indiehackers",
  "indiehackersindia",
  "DesiFounder",
  "indianstartups",
  // Business opportunities
  "smallbusiness",
  "Business_Ideas",
  "acquiresaas",
  // Developer opportunities
  "developersIndia",
  "webdev",
  "programming",
  "webdevjobs"
];

export const OPPORTUNITY_KEYWORDS = [
  'hiring',
  'looking for',
  'seeking',
  'need a',
  'need an',
  'want to hire',
  'freelance',
  'freelancer',
  'contractor',
  'contract',
  'paid',
  'budget',
  'compensation',
  'salary',
  'collaboration',
  'collab',
  'partner',
  'cofounder',
  'co-founder',
  'join',
  'opportunity',
  'project',
  'build',
  'develop',
  'developer',
  'programmer',
  'engineer'
];

export const TECH_KEYWORDS = [
  'react',
  'reactjs',
  'next',
  'nextjs',
  'java',
  'spring boot',
  'frontend',
  'typescript',
  'javascript',
  'node',
  'nodejs',
  'full stack',
  'fullstack',
  'backend',
  'api',
  'database',
  'mongodb',
  'postgresql',
  'mysql',
  'aws',
  'cloud',
  'docker',
  'kubernetes',
  'microservices',
  'rest api',
  'graphql',
  'saas'
];

export const EXCLUSION_KEYWORDS = [
  '[for hire]',
  '[for-hire]',
  'for hire',
  'for-hire',
  'i\'m available',
  'i am available',
  'i offer',
  'i can help',
  'i can build',
  'i specialize',
  'my services',
  'my portfolio',
  'hire me',
  'available for',
  'looking for work',
  'seeking work',
  'open to work',
  'rate:',
  'hourly rate',
  'per hour',
  '/hr',
  '/hour',
  'contact me',
  'dm me',
  'message me',
  'email me',
  'portfolio',
  'behance',
  'dribbble',
  'github.com',
  'years of experience',
  'i\'ve been',
  'i have been',
  'looking for partner',
  'looking for a partner',
  'seeking partner',
  'seeking a partner',
  'want to partner',
  'partner with',
  'partner up',
  'developer looking to partner',
  'looking to partner with',
  'i\'m looking to partner',
  'i am looking to partner'
];

// GitHub Configuration
export const GITHUB_SKILL_KEYWORDS = [
  'java',
  'spring',
  'spring boot',
  'node',
  'nestjs',
  'react',
  'nextjs',
  'typescript',
  'mongodb',
  'api',
  'backend',
  'frontend',
  'fullstack'
];


// HackerNews Configuration
export const HACKERNEWS_TARGET_PATTERNS = [
  'ask hn: who is hiring',
  'ask hn: who wants to be hired',
  'freelancer? seeking freelancer'
];

